apiVersion: v1
kind: Service
metadata:
  name: new-camp-ui-backend
  labels:
    app: new-camp-ui
spec:
  type: NodePort
  selector:
    app: new-camp-ui
    tier: web
  ports:
  - name: httpuiport
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: httpsuiport
    protocol: TCP
    port: 443
    targetPort: 8080